### ISSUE TITLE
JsonReaderException: 'Could not convert string to DateTime'

### ISSUE THREAD

**Issue by s0llvan** [jellyfin/TMDbLib#522] opened 2024-12-06 23:32 UTC
### This issue respects the following points:

- [x] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [x] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [x] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [x] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [x] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

I haven't used Jellyfin for several weeks.
I pulled the latest Docker image and updated it.
I added movies and series, then tried to edit the metadata using 'Identify' function but it didn't work, and I saw these errors in the logs.
I tried completely reinstalling the container from scratch and noticed the same errors in the logs.
Same errors with any metadata providers.

### Reproduction steps

Install server with [docker-compose.yml](https://jellyfin.org/docs/general/installation/container#docker)

**OR**

Identify any show or movie

### What is the current _bug_ behavior?

Metadata doesn't updated

### What is the expected _correct_ behavior?

Metadata updated

### Jellyfin Server version

10.10.0+

### Specify the build version

10.10.3

### Environment

```markdown
- OS: Debian 12
- Linux Kernel: 6.6
- Virtualization: Docker
- Clients: Browser
- Browser: Firefox, Chromium
- FFmpeg Version: unknown
- Playback Method: /
- Hardware Acceleration: none
- GPU Model: none
- Plugins: none
- Reverse Proxy: none
- Base URL: none
- Networking: Host
- Storage:local
```

### Jellyfin logs

```shell
jellyfin  | [00:16:31] [INF] [21] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/media/external/Series/AVC/Kaamelott/Saison 1/Kaamelott.S01E66.FRENCH.1080p.BluRay.x264.AC3-Dam.mkv" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
jellyfin  | [00:16:31] [ERR] [22] MediaBrowser.Providers.TV.SeriesMetadataService: Error in TheMovieDb
jellyfin  | Newtonsoft.Json.JsonReaderException: Could not convert string to DateTime: 2020-08-19 12:35:02 UTC. Path 'videos.results[0].published_at', line 1, position 35406.
jellyfin  |    at Newtonsoft.Json.JsonReader.ReadDateTimeString(String s)
jellyfin  |    at Newtonsoft.Json.JsonTextReader.FinishReadQuotedStringValue(ReadType readType)
jellyfin  |    at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
jellyfin  |    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
jellyfin  |    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
jellyfin  |    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
jellyfin  |    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
jellyfin  |    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
jellyfin  |    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
jellyfin  |    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
jellyfin  |    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
jellyfin  |    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
jellyfin  |    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
jellyfin  |    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
jellyfin  |    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
jellyfin  |    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
jellyfin  |    at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
jellyfin  |    at TMDbLib.Utilities.Serializer.TMDbJsonSerializer.Deserialize(Stream source, Type type)
jellyfin  |    at TMDbLib.Utilities.Serializer.SerializerExtensions.Deserialize[T](ITMDbSerializer serializer, Stream source)
jellyfin  |    at TMDbLib.Rest.RestResponse`1.GetDataObject()
jellyfin  |    at TMDbLib.Client.TMDbClient.GetTvShowAsync(Int32 id, TvShowMethods extraMethods, String language, String includeImageLanguage, CancellationToken cancellationToken)
jellyfin  |    at MediaBrowser.Providers.Plugins.Tmdb.TmdbClientManager.GetSeriesAsync(Int32 tmdbId, String language, String imageLanguages, CancellationToken cancellationToken)
jellyfin  |    at MediaBrowser.Providers.Plugins.Tmdb.TV.TmdbSeriesProvider.GetMetadata(SeriesInfo info, CancellationToken cancellationToken)
jellyfin  |    at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, Boolean replaceData, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
jellyfin  | [00:16:31] [INF] [33] Emby.Server.Implementations.MediaEncoder.EncodingManager: Skipping chapter image extraction for Kaamelott.S01E66.FRENCH as the average chapter duration 0 was lower than the minimum threshold 10000000
```

### FFmpeg logs

```shell
[2024-12-07 00:03:08.172 +01:00] [INF] [31] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/media/external/Movies/AVC/Good.Boys.2019.MULTi.TRUEFRENCH.1080p.HDLight.x264.AC3-EXTREME.mkv\" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format"
[2024-12-07 00:03:08.516 +01:00] [ERR] [24] MediaBrowser.Providers.Movies.MovieMetadataService: Error in "TheMovieDb"
Newtonsoft.Json.JsonReaderException: Could not convert string to DateTime: 2021-05-10 12:30:00 UTC. Path 'videos.results[0].published_at', line 1, position 69678.
   at Newtonsoft.Json.JsonReader.ReadDateTimeString(String s)
   at Newtonsoft.Json.JsonTextReader.FinishReadQuotedStringValue(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadStringValue(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadAsDateTime()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at TMDbLib.Utilities.Serializer.TMDbJsonSerializer.Deserialize(Stream source, Type type)
   at TMDbLib.Utilities.Serializer.SerializerExtensions.Deserialize[T](ITMDbSerializer serializer, Stream source)
   at TMDbLib.Rest.RestResponse`1.GetDataObject()
   at TMDbLib.Client.TMDbClient.GetMovieAsync(String imdbId, String language, String includeImageLanguage, MovieMethods extraMethods, CancellationToken cancellationToken)
   at TMDbLib.Client.TMDbClient.GetMovieAsync(Int32 movieId, String language, String includeImageLanguage, MovieMethods extraMethods, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Plugins.Tmdb.TmdbClientManager.GetMovieAsync(Int32 tmdbId, String language, String imageLanguages, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Plugins.Tmdb.Movies.TmdbMovieProvider.GetMetadata(MovieInfo info, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, Boolean replaceData, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
```

### Relevant screenshots or videos
https://github.com/user-attachments/assets/f650e5b0-c1da-4916-bc7e-a278fee868be

**Comment by obychyk** [comment] 2024-12-07 00:13
Looks like it crashes [here](https://github.com/jellyfin/TMDbLib/blob/7748d9fce05a7d81a0dc979b524890f49dc01353/TMDbLib/Utilities/Serializer/TMDbJsonSerializer.cs#L40):
```
public object Deserialize(Stream source, Type type)
{
    using StreamReader sr = new StreamReader(source, _encoding, false, 4096, true);
    using JsonTextReader jr = new JsonTextReader(sr);

    return _serializer.Deserialize(jr, type);
}
```

Making a wild suggestion (new to Jellyfin and its codebase) - maybe it makes sense to add a base converter that could check if the value can be indeed taken from a json payload (I've checked the [existing converters](https://github.com/jellyfin/TMDbLib/blob/7748d9fce05a7d81a0dc979b524890f49dc01353/TMDbLib/Utilities/Serializer/TMDbJsonSerializer.cs#L18) - doesn't seem like you have any try-catch blocks for the case mentioned in  the description)?

**Comment by alex6dj** [comment] 2024-12-07 06:51
Same here. Dont know exactly how it behaved before but seems to be related with the UTC in the `published_at` string. The problems in my case only affect the use of `MovieMethods.Videos` and `TvShowMethods.Videos` in extraMethods for movies an tvshows. After removing that extra everything works again. For now I can live without trailers.

Note: Using ´tmDbClient.GetMovieVideosAsync(movieId)´ end with the same exception, the problem is TMDB related.

**Comment by VigibotDev** [comment] 2024-12-07 10:25
On OLD JSON :

release_date = "2024-07-07T00:00:00.000Z"

Now it's "clean" = "2024-01-10" but Jellyfin TMDb API client don't like it.

I can patch the data on the fly with MITM Proxy to wait real Jellyfin developer solution.

You can get the Jellyfin request here :

https://api.themoviedb.org/3/movie/626412?language=fr&include_image_language=fr%2Cnull%2Cen&append_to_response=credits%2Cimages%2Ckeywords%2Creleases%2Cvideos&api_key=4219e299c89411838049ab0dab19ebd5

Look at this OLD JSON to compare :

[626412.json](https://github.com/user-attachments/files/18047969/626412.json)

**Comment by VigibotDev** [comment] 2024-12-07 10:39
OLD format because I have all TMDb JSON on my server :

![Image](https://github.com/user-attachments/assets/a3cdf1d1-ff50-4c3e-b889-c0c867294749)

NEW TMDb format :
![Image](https://github.com/user-attachments/assets/4c2a6184-005e-4a79-847c-99c55c16417e)

**Comment by Shadowghost** [comment] 2024-12-07 10:50
Once they confirmed it is an intentional and permanent format change, we'll adopt the `CustomDatetimeFormatConverter` to the new format and release a fix.

TMDB forum thread for reference: https://www.themoviedb.org/talk/675427102a0e9c79f19b8d0e

**Comment by VigibotDev** [comment] 2024-12-07 10:51
For information, if I use my own old request URL :
https://api.themoviedb.org/3/movie/626412?append_to_response=credits,external_ids,release_dates,translations,images,videos&include_image_language=fr,null,en&language=fr-FR&api_key=4219e299c89411838049ab0dab19ebd5
This give the old date format and structure can work with the actual code. Strange

**Comment by VigibotDev** [comment] 2024-12-07 10:58
Jellyfin use :

https://api.themoviedb.org/3/movie/626412
?language=fr
&include_image_language=fr,null,en

&append_to_response=
credits,
images,
keywords,
releases,
videos

&api_key=4219e299c89411838049ab0dab19ebd5


I use :
https://api.themoviedb.org/3/movie/626412
&include_image_language=fr,null,en&language=fr-FR

?append_to_response=
credits,
external_ids,
release_dates,
translations,
images,
videos

&api_key=4219e299c89411838049ab0dab19ebd5

**Comment by VigibotDev** [comment] 2024-12-07 11:03
Found it. Just add "release_dates" into ?append_to_response= to repair Jellyfin TMDb client.
I try with MITM Proxy....

**Comment by Franiix** [comment] 2024-12-07 12:08
It's very problem bug this D:

**Comment by VigibotDev** [comment] 2024-12-07 12:17
OK I found my temporary workaround.

mitmdump -v -B "|published_at|published_at_disabled" > /tmp/mitmdump.log &

Just rename the published_at part of JSON and my Jellyfin work with TMDb.

**Comment by Franiix** [comment] 2024-12-07 12:46
> OK I found my temporary workaround.
> 
> mitmdump -v -B "|published_at|published_at_disabled" > /tmp/mitmdump.log &
> 
> Just rename the published_at part of JSON and my Jellyfin work with TMDb. I don't need trailer date lol

This command lunch in terminal?

**Comment by VigibotDev** [comment] 2024-12-07 12:55
Sorry, this is more of a debugging option for any application and not a standard command line. This is MITM proxy (a small software) to "spy" on outgoing requests made by my server. You can install it (on a Raspberry PI) and use it to fix web traffic on the fly. I can give a procedure to add it between Jellyfin and the Internet if you are interested

**Comment by Franiix** [comment] 2024-12-07 13:01
> Sorry, this is more of a debugging option for any application and not a standard command line. This is MITM proxy (a small software) to "spy" on outgoing requests made by any server or computers. You can install it (for example on a Raspberry PI) and use it to fix web traffic on the fly. I can give a procedure to add it between Jellyfin and the Internet if you are interested. Now my jellyfin work. I use MITM to use my own TMDb API Key instead of developers one, and I added this workaround because I can't live without TMDb on Jellyfin. All other are crap (not as open data) for my usage. If TMDb have bad information, I just edit TMDb itself, TMDb is the only one relies on and real movie/show releases life.

Thanks, but i waiting fix tmdb

**Comment by mmedic** [comment] 2024-12-07 16:21
> Once they confirmed it is an intentional and permanent format change, we'll adopt the `CustomDatetimeFormatConverter` to the new format and release a fix.
> 
> TMDB forum thread for reference: https://www.themoviedb.org/talk/675427102a0e9c79f19b8d0e

Why not handle multiple date formats so it backwards compatible?

**Comment by Shadowghost** [comment] 2024-12-07 19:53
> Why not handle multiple date formats so it backwards compatible?

Because an API should not have variable types for the same entity. This was an unintended behviour on TMDB side which was caused by a library upgrade. They pushed a fix but it will take ~8h until all caches are refreshed

**Comment by vreelb** [comment] 2024-12-07 20:14
> should not

The nature of using 3rd party data is that sometimes they provide bad data or are designed sub-optimally. In this case If both formats are handled the next time this accidentally happens nothing on the Jellyfin side will break. They _should_ test their changes before they push them  out too.

**Comment by lluisd** [comment] 2024-12-08 00:18
same problem here with new movies not being identifid due tot this bug

**Comment by kandykarter** [comment] 2024-12-08 06:12
Image downloads work again properly, but refreshing metadata/people still throws this error

`[2024-12-07 22:10:03.889 -08:00] [ERR] [9] MediaBrowser.Providers.Movies.MovieMetadataService: Error in "TheMovieDb"
Newtonsoft.Json.JsonReaderException: Could not convert string to DateTime: 2018-12-10 18:13:28 UTC. Path 'videos.results[0].published_at', line 1, position 39102.
   at Newtonsoft.Json.JsonReader.ReadDateTimeString(String s)
   at Newtonsoft.Json.JsonTextReader.FinishReadQuotedStringValue(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadStringValue(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadAsDateTime()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at TMDbLib.Utilities.Serializer.TMDbJsonSerializer.Deserialize(Stream source, Type type)
   at TMDbLib.Utilities.Serializer.SerializerExtensions.Deserialize[T](ITMDbSerializer serializer, Stream source)
   at TMDbLib.Rest.RestResponse`1.GetDataObject()
   at TMDbLib.Client.TMDbClient.GetMovieAsync(String imdbId, String language, String includeImageLanguage, MovieMethods extraMethods, CancellationToken cancellationToken)
   at TMDbLib.Client.TMDbClient.GetMovieAsync(Int32 movieId, String language, String includeImageLanguage, MovieMethods extraMethods, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Plugins.Tmdb.TmdbClientManager.GetMovieAsync(Int32 tmdbId, String language, String imageLanguages, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Plugins.Tmdb.Movies.TmdbMovieProvider.GetMetadata(MovieInfo info, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, Boolean replaceData, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)`

**Comment by TimGels** [comment] 2024-12-08 16:03
I cannot reproduce this problem anymore. Can you try again @kandykarter ?

**Comment by kandykarter** [comment] 2024-12-08 16:04
You're correct, it now seems to have worked. Perhaps the cache thing at TMDB took a while longer than the forecasted 8 hours to fully complete. Thank you for checking in.

**Comment by TimGels** [comment] 2024-12-08 16:06
We will be closing this issue then. Thank you for the quick reply!

**Comment by VigibotDev** [comment] 2024-12-08 16:15
It's done (from my side) because the jellyfin request :

https://api.themoviedb.org/3/movie/626412?language=fr&include_image_language=fr%2Cnull%2Cen&append_to_response=credits%2Cimages%2Ckeywords%2Creleases%2Cvideos&api_key=4219e299c89411838049ab0dab19ebd5

Show TMDb returned to the old format :

published_at: "2024-11-18T04:47:37.000Z"

**Closed** 2024-12-08 16:15 UTC
Labels: bug
